// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AddressDbContext))]
    [Migration("20211201152653_Add_FamilyPrintListRelation")]
    partial class Add_FamilyPrintListRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("DAL.Entities.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOverride")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<int>("Title")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("DAL.Entities.FamilyPrintListRelation", b =>
                {
                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrintListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FamilyId", "PrintListId");

                    b.HasIndex("PrintListId");

                    b.ToTable("FamilyPrintListRelation");
                });

            modelBuilder.Entity("DAL.Entities.PrintList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrintLists");
                });

            modelBuilder.Entity("DAL.Entities.FamilyPrintListRelation", b =>
                {
                    b.HasOne("DAL.Entities.Family", "Family")
                        .WithMany("FamilyPrintListRelations")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.PrintList", "PrintList")
                        .WithMany("FamilyPrintListRelations")
                        .HasForeignKey("PrintListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("PrintList");
                });

            modelBuilder.Entity("DAL.Entities.Family", b =>
                {
                    b.Navigation("FamilyPrintListRelations");
                });

            modelBuilder.Entity("DAL.Entities.PrintList", b =>
                {
                    b.Navigation("FamilyPrintListRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
